### ISSUE TITLE
アプリ名を考える

### ISSUE THREAD

**Issue by nnsnodnb** [nnsnodnb/ContiningTweet#5]

**Comment by Kkmy** [comment]
迅速にツイートができる言うことだったので最速の鳥からハヤブサ、もしくはFalconなど如何でしょうか。
コメント日本語でもいいよね…？

**Comment by nnsnodnb** [comment]
@Kkmy
なるほど。あとツイートってわかるようにできればそれっぽい名前にしたい

**Comment by Kkmy** [comment]
一応Twitterのアイコンに引っ掛けて鳥つながりだけど、TweetDeckみたいに直接名前に入れるってことかな？

**Comment by nnsnodnb** [comment]
@Kkmy
イメージ的にはそう。そしてアプリアイコンに表示できる文字列長も考慮しないといけない

**Comment by nnsnodnb** [comment]
iOS8.x: マルチバイト6文字、シングルバイト12文字
iOS9.x: マルチバイト7文字、シングルバイト12文字

**Comment by Kkmy** [comment]
アプリアイコンに文字入れたい？入れなくてもいいかな〜って思ってたんだけど

**Comment by nnsnodnb** [comment]
@Kkmy
アプリアイコンに文字っていうのがアプリ名ってことだ。日本語下手で申し訳ない

**Comment by Kkmy** [comment]
アイコンの下にある文字ってことか
